# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f373621dfed756e374c6b052dd917e2926ead609918502a3ca85783a7103e20f833edcf19eb4f0200768fb3b1e1cec17ea3ada853c5b2f8817ad4bbedc2fcade

test:
  secret_key_base: ceed9ec2d84c1dffba906d6769a04b71e1f432806e75e77a7a639665a189dbbce52dd6e5c3eb656d1d3de3679816aef64ee7bb98d1ebab7d986808c82655db29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
